<Project>
	<!-- ============================= -->
	<!-- Global project configuration -->
	<!-- ============================= -->

	<PropertyGroup Label="Common properties">
		<Product>Integration Aeration Sterilize</Product>
		<Copyright>Copyright (c) 2026-2027 AIX.</Copyright>
		<Authors>AIX</Authors>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<NoWarn>8981, CS0660, CS0661</NoWarn>
	</PropertyGroup>

	<PropertyGroup Label="Common Naming and Coding Convention">

		<!--Code Quality -> Start SonarQube Analysis-->
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>All</AnalysisMode>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>

		<!--<TreatWarningsAsErrors Condition="'$(CI)' == 'true'">true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild Condition="'$(CI)' == 'true'">true</EnforceCodeStyleInBuild>-->
	</PropertyGroup>

	<!--Apply library specific for all of the projects-->
	<ItemGroup Condition="'$(MSBuildProjectExtension)' != '.dcproj'">
		<PackageReference Include="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>